// This is free and unencumbered software released into the public domain.
// For more information, please refer to <http://unlicense.org/>

// This file describes the C API you can use to make your decision components
// (schedulers, workload injectors...) callable by Batsim as dynamic libraries.

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>

// These are the flags supported by batsim_edc_init() argument.
#define BATSIM_EDC_FORMAT_BINARY 0x1 // Format is flatbuffers's binary format. Messages are pointers to buffers generated by a flatbuffers library.
#define BATSIM_EDC_FORMAT_JSON 0x2 // Format is flatbuffer's JSON format. Messages are NULL-terminated C strings with JSON content.

/**
 * @brief The batsim_edc_init() function is called by Batsim to initialize your external decision component.
 * @details This is typically used to initialize global data structures to de/serialize messages and to take decisions later on.
 *
 * @param[in] data The initialization data of your decision component. This is retrieved from Batsim's command-line arguments.
 * @param[in] size The size of your initialization data. This is retrieved from Batsim's command-line arguments.
 * @param[in,out] flags These flags tell Batsim which message format should be used.
 * @param[out] reply_data The initialization reply buffer sent back to Batsim.
 * @param[out] reply_size The size of the initialization reply buffer.
 * @return Zero if and only if you could initialize yourself successfully.
 */
uint8_t batsim_edc_init(
    const uint8_t * data,
    uint32_t size,
    uint32_t * flags,
    uint8_t ** reply_data,
    uint32_t * reply_size);

/**
 * @brief The batsim_edc_deinit() function is called by Batsim when it stops calling your decision component.
 * @details This is typically used to deallocate any memory allocated by batsim_edc_init() or batsim_edc_take_decisions().
 * @return Zero if and only if you could deinitialize yourself successfully.
 */
uint8_t batsim_edc_deinit();

/**
 * @brief The batsim_edc_take_decisions() function is called by Batsim when it asks you to take decisions.
 *
 * @param[in] what_happened A Batsim protocol message that contains what happened in the simulation since the previous call to your decision component
 *                          (that is to say, since last batsim_edc_take_decisions() call or since the initial batsim_edc_init() at the beginning of the simulation).
 * @param[in] what_happened_size The size (in bytes) of the what_happened input buffer.
 * @param[out] decisions A Batsim protocol message that contains the decisions taken by this function.
 * @param[out] decisions_size The size (in bytes) of the decisions output buffer.
 * @return Zero if and only if you could take decisions.
 */
uint8_t batsim_edc_take_decisions(
    const uint8_t * what_happened,
    uint32_t what_happened_size,
    uint8_t ** decisions,
    uint32_t * decisions_size);

#ifdef __cplusplus
}
#endif